### ISSUE TITLE
README.md formatting

### ISSUE THREAD

**Issue by justinGilmer** [zijiewu3/mbuild_ONA#1]
Hey everyone! Awesome first mBuild plug-in! I noticed some things in the readme file that could be edited to improve its readability.

```
A preliminary implementation of the ONA model (Ghobadi and Jayaraman, Soft Matter, 2016, 12, 2276) on MoSDeF platform (https://mosdef.org).

Guide for testers: 1.Create a new conda env, and install mbuild and foyer. In linux shell, conda create -n mosdef35 -c mosdef -c conda-forge -c omnia mbuild foyer python=3.7 openbabel 2.Install mbuild_ONA. Download or clone this repo and run pip install -e . 3.Refer to example.py or example_from_mbuild.py
```

First, when creating numbered lists, you need to have them on new lines for the markdown rendering engine to recognize it. for Example:

**Guide for testers: 1.Create a new conda env, and install mbuild and foyer. In linux shell, conda create -n mosdef35 -c mosdef -c conda-forge -c omnia mbuild foyer python=3.7 openbabel 2.Install mbuild_ONA. Download or clone this repo and run pip install -e . 3.Refer to example.py or example_from_mbuild.py** 

I would structure the readme file like this below:
```
A preliminary implementation of the ONA model (Ghobadi and Jayaraman, Soft Matter, 2016, 12, 2276) on MoSDeF platform (https://mosdef.org).

Guide for testers:
1. Create a new conda env, and install mbuild and foyer. 
    * In linux shell:
      * `conda create -n mosdef37 -c mosdef -c conda-forge -c omnia mbuild foyer python=3.7 openbabel`
1. Install mbuild_ONA.
1. Refer to `example.py` or `example_from_mbuild.py`
```

 Will now turn in to this:
--------

A preliminary implementation of the ONA model (Ghobadi and Jayaraman, Soft Matter, 2016, 12, 2276) on MoSDeF platform (https://mosdef.org).

Guide for testers:
1. Create a new conda env, and install mbuild and foyer. 
    * In linux shell:
      * `conda create -n mosdef37 -c mosdef -c conda-forge -c omnia mbuild foyer python=3.7 openbabel`
1. Install mbuild_ONA.
    * Download or clone this repo and run `pip install -e .`
1. Refer to `example.py` or `example_from_mbuild.py`

#### Just some notes
You do not have to number things yourself, leaving them all as `1.` will suffice and markdown will render the numbers properly. No need to keep editing them yourself!

`*` are used for bullet points, put spaces before them to denote how tabbed they are

Back-tics \` put the text contained between them in a shell-like style, useful to show commands and such.

In the grey large section above, show the raw text of the readme file with my changes in it. You can then use that as a reference when editing the readme!

here is a great set of information about markdown and how GitHub uses it!
https://guides.github.com/features/mastering-markdown/#intro

**Comment by zijiewu3** [comment]
Thanks a lot Justin! README.md has been updated.
